title: "Statistische Modellierung"
institute: "FOM Standort"
author: "Dozent:in"
from: markdown+emoji
lang: de-DE
slide-number: c
format: 
  revealjs:
    footer: "Statistische Modellierung | Dozent:in"
    chalkboard: true
    html-math-method: katex
    main-font: Arial
    width: 1920
    height: 1080 #    height: 1200 oder 1080 
    margin: 0
    history: true
    center: false
    slide-number: true
    theme:
      - colors.scss
      - fontsstyles.scss
      - fom.scss # FOM Layout
#      - fom-dls.scss # DLS Layout
engine: knitr
webr: 
  show-startup-message: false    # Disable displaying status of webR initialization
  packages: ['mosaic']
filters:
  - webr